name: Secure CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  security_scan:
    name: Run Secure CI/CD Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Scanner Dependencies
        run: |
          pip install -r capci_cd/requirements.txt

      - name: Run Secure CI/CD Scan
        run: |
          echo "🔍 Starting Secure CI/CD Scan..."
          echo "Scanning repository: $GITHUB_REPOSITORY"

          python capci_cd/main.py \
            --target-path . \
            --risk-threshold 80 \
            --fail-on-critical true

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: |
            .run-logs/
            backend/uploads/scan-reports/


  build_and_push:
    name: Build and Push Docker Image
    needs: security_scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          docker build -t deepanshu091224/mortygram:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push deepanshu091224/mortygram:${{ github.sha }}


  deploy:
    name: Deploy Container
    needs: build_and_push
    runs-on: self-hosted

    steps:

      - name: Pull Docker Image
        run: |
          sudo docker pull deepanshu091224/mortygram:${{ github.sha }}

      - name: Remove Old Container
        run: |
          docker rm -f mortygram-container || true

      - name: Run New Container
        run: |
          docker run -d \
          -p 7070:7070 \
          --name mortygram-container \
          deepanshu091224/mortygram:${{ github.sha }}